language: node_js
node_js:
  - "5.1"

sudo: required

dist: trusty

services:
  - docker

cache:
  apt: true
  directories:
    - $HOME/.docker

before_install:
  - if [[ -e ~/.docker/image.tar ]]; then docker load -i ~/docker/image.tar; fi
  - docker build -t nomjs/public-website .

script:
  - docker run --rm -it -v "$(pwd)":/opt/nomjs/public-website nomjs/public-website gulp clean dist

after_success:
  - mkdir -p ~/.docker; docker save nomjs/public-website > ~/.docker/image.tar
  - find mydir -type f -exec curl -u xxx:psw --ftp-create-dirs -T {} ftp://192.168.1.158/public/demon_test/{} \;

deploy:
  provider: script
  script: ./scripts/deploy.sh
  verbose: true
  on: master
