sudo: required

services:
  - docker

before_install:
  - docker build -t nomjs/public-website .

script:
  - docker run --rm -v $(pwd):/opt/nomjs/public-website nomjs/public-website gulp dist

deploy:
  provider: azure_web_apps
  on: master
